name: Publish to Sigrid
on:
  push:
    branches:
      - main

jobs:
  sigridci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@main
        with:
          customer: examplecustomername
          system: examplesystemname
          publishonly: true
        env:
          SIGRID_CI_TOKEN: "${{ eyJraWQiOiJzaWcta2V5IiwiYWxnIjoiUlMyNTYifQ.eyJqdGkiOiIxNDRhYjBkZS0wODAxLTQyYWUtYjYwMi0zMWFkNTI3NjM2Y2EiLCJzdWIiOiI4YzU0MDkxNi1hYjBmLTQ2MGItYWViOC0yMjNhZDZjOTQzNzEiLCJpc3MiOiJodHRwOi8vYXV0aGFwaTo4MDgwIiwiaWF0IjoxNzE0OTAzMzgzLCJleHAiOjE3NDY0MzkzODMsImNvZ25pdG86Z3JvdXBzIjpbInV0c3QiXSwidG9rZW5fdXNlIjoiYWNjZXNzIiwic2NvcGUiOiIiLCJ1c2VybmFtZSI6IjhjNTQwOTE2LWFiMGYtNDYwYi1hZWI4LTIyM2FkNmM5NDM3MSJ9.TrCSCIspIT0Is0yRroE4cqIpeFzhtx4-w1jJ0FMXwVgakG7b1R_M3VFdBK1RcBAWVyE_1qj-Pf--3lfsf94PfuSr8rY227dxzYXw43T3Qn7U0qG5aJs52R2mlCzm66536csAA-BxPWzXHvCWWxXwLszupdB07kEkxcUTI8aoHMor9DMEhutoxkvrFOIbgU-ykbaS1j426ccJOrjarwypTRe7M2wtmboc09JcGN2ocb5TvPyicao7jXtqDD88gUia_5L42BFC2rXH0hT_w8I_KrC5tJcK8G2pSN4fdDG544r93Khj6TygtpEvyOTnwAC07v_7CTd5AHtQNvsVjBItbQ }}"
